import type { Move } from './types.js'

export const MOVES = {
  // --- Signature Moves: embrak (fire) ---
  inferno_rush: {
    move_id: 'inferno_rush',
    name: 'Inferno Rush',
    type: 'fire',
    category: 'damage',
    power: 90,
    accuracy: 100,
    priority: 0,
    crit_enabled: true,
    inflicted_status: null,
    status_application_mode: null,
    status_proc_numerator: null,
    status_proc_denominator: null,
  },
  searing_fang: {
    move_id: 'searing_fang',
    name: 'Searing Fang',
    type: 'fire',
    category: 'damage_plus_status',
    power: 65,
    accuracy: 90,
    priority: 0,
    crit_enabled: false,
    inflicted_status: 'burn',
    status_application_mode: 'rolled',
    status_proc_numerator: 1,
    status_proc_denominator: 3,
  },

  // --- Signature Moves: thornvine (grass) ---
  thorn_lash: {
    move_id: 'thorn_lash',
    name: 'Thorn Lash',
    type: 'grass',
    category: 'damage',
    power: 85,
    accuracy: 100,
    priority: 0,
    crit_enabled: true,
    inflicted_status: null,
    status_application_mode: null,
    status_proc_numerator: null,
    status_proc_denominator: null,
  },
  spore_cloud: {
    move_id: 'spore_cloud',
    name: 'Spore Cloud',
    type: 'grass',
    category: 'pure_status',
    power: 0,
    accuracy: 90,
    priority: 0,
    crit_enabled: false,
    inflicted_status: 'paralysis',
    status_application_mode: 'guaranteed',
    status_proc_numerator: null,
    status_proc_denominator: null,
  },

  // --- Signature Moves: torrentis (water) ---
  hydro_slam: {
    move_id: 'hydro_slam',
    name: 'Hydro Slam',
    type: 'water',
    category: 'damage',
    power: 100,
    accuracy: 90,
    priority: 0,
    crit_enabled: true,
    inflicted_status: null,
    status_application_mode: null,
    status_proc_numerator: null,
    status_proc_denominator: null,
  },
  riptide: {
    move_id: 'riptide',
    name: 'Riptide',
    type: 'water',
    category: 'damage_plus_status',
    power: 70,
    accuracy: 95,
    priority: 0,
    crit_enabled: false,
    inflicted_status: 'paralysis',
    status_application_mode: 'rolled',
    status_proc_numerator: 1,
    status_proc_denominator: 5,
  },

  // --- Signature Moves: glacior (ice) ---
  glacial_spike: {
    move_id: 'glacial_spike',
    name: 'Glacial Spike',
    type: 'ice',
    category: 'damage',
    power: 90,
    accuracy: 100,
    priority: 0,
    crit_enabled: true,
    inflicted_status: null,
    status_application_mode: null,
    status_proc_numerator: null,
    status_proc_denominator: null,
  },
  blizzard_rush: {
    move_id: 'blizzard_rush',
    name: 'Blizzard Rush',
    type: 'ice',
    category: 'damage_plus_status',
    power: 75,
    accuracy: 85,
    priority: 0,
    crit_enabled: false,
    inflicted_status: 'freeze',
    status_application_mode: 'rolled',
    status_proc_numerator: 1,
    status_proc_denominator: 5,
  },

  // --- Signature Moves: drakonyx (dragon) ---
  dragon_rage: {
    move_id: 'dragon_rage',
    name: 'Dragon Rage',
    type: 'dragon',
    category: 'damage',
    power: 100,
    accuracy: 95,
    priority: 0,
    crit_enabled: true,
    inflicted_status: null,
    status_application_mode: null,
    status_proc_numerator: null,
    status_proc_denominator: null,
  },
  scale_storm: {
    move_id: 'scale_storm',
    name: 'Scale Storm',
    type: 'dragon',
    category: 'damage',
    power: 80,
    accuracy: 100,
    priority: 0,
    crit_enabled: true,
    inflicted_status: null,
    status_application_mode: null,
    status_proc_numerator: null,
    status_proc_denominator: null,
  },

  // --- Variable Pool Moves: fire ---
  fire_blast: {
    move_id: 'fire_blast',
    name: 'Fire Blast',
    type: 'fire',
    category: 'damage',
    power: 110,
    accuracy: 85,
    priority: 0,
    crit_enabled: true,
    inflicted_status: null,
    status_application_mode: null,
    status_proc_numerator: null,
    status_proc_denominator: null,
  },
  flamethrower: {
    move_id: 'flamethrower',
    name: 'Flamethrower',
    type: 'fire',
    category: 'damage_plus_status',
    power: 90,
    accuracy: 100,
    priority: 0,
    crit_enabled: true,
    inflicted_status: 'burn',
    status_application_mode: 'rolled',
    status_proc_numerator: 1,
    status_proc_denominator: 10,
  },
  ember: {
    move_id: 'ember',
    name: 'Ember',
    type: 'fire',
    category: 'damage_plus_status',
    power: 40,
    accuracy: 100,
    priority: 0,
    crit_enabled: false,
    inflicted_status: 'burn',
    status_application_mode: 'rolled',
    status_proc_numerator: 1,
    status_proc_denominator: 3,
  },
  will_o_wisp: {
    move_id: 'will_o_wisp',
    name: 'Will-O-Wisp',
    type: 'fire',
    category: 'pure_status',
    power: 0,
    accuracy: 85,
    priority: 0,
    crit_enabled: false,
    inflicted_status: 'burn',
    status_application_mode: 'guaranteed',
    status_proc_numerator: null,
    status_proc_denominator: null,
  },

  // --- Variable Pool Moves: grass ---
  solar_strike: {
    move_id: 'solar_strike',
    name: 'Solar Strike',
    type: 'grass',
    category: 'damage',
    power: 100,
    accuracy: 90,
    priority: 0,
    crit_enabled: true,
    inflicted_status: null,
    status_application_mode: null,
    status_proc_numerator: null,
    status_proc_denominator: null,
  },
  razor_leaf: {
    move_id: 'razor_leaf',
    name: 'Razor Leaf',
    type: 'grass',
    category: 'damage',
    power: 55,
    accuracy: 95,
    priority: 0,
    crit_enabled: true,
    inflicted_status: null,
    status_application_mode: null,
    status_proc_numerator: null,
    status_proc_denominator: null,
  },
  vine_whip: {
    move_id: 'vine_whip',
    name: 'Vine Whip',
    type: 'grass',
    category: 'damage',
    power: 45,
    accuracy: 100,
    priority: 0,
    crit_enabled: false,
    inflicted_status: null,
    status_application_mode: null,
    status_proc_numerator: null,
    status_proc_denominator: null,
  },
  stun_spore: {
    move_id: 'stun_spore',
    name: 'Stun Spore',
    type: 'grass',
    category: 'pure_status',
    power: 0,
    accuracy: 75,
    priority: 0,
    crit_enabled: false,
    inflicted_status: 'paralysis',
    status_application_mode: 'guaranteed',
    status_proc_numerator: null,
    status_proc_denominator: null,
  },

  // --- Variable Pool Moves: water ---
  hydro_pump: {
    move_id: 'hydro_pump',
    name: 'Hydro Pump',
    type: 'water',
    category: 'damage',
    power: 110,
    accuracy: 80,
    priority: 0,
    crit_enabled: true,
    inflicted_status: null,
    status_application_mode: null,
    status_proc_numerator: null,
    status_proc_denominator: null,
  },
  water_pulse: {
    move_id: 'water_pulse',
    name: 'Water Pulse',
    type: 'water',
    category: 'damage',
    power: 60,
    accuracy: 100,
    priority: 0,
    crit_enabled: false,
    inflicted_status: null,
    status_application_mode: null,
    status_proc_numerator: null,
    status_proc_denominator: null,
  },
  aqua_jet: {
    move_id: 'aqua_jet',
    name: 'Aqua Jet',
    type: 'water',
    category: 'damage',
    power: 40,
    accuracy: 100,
    priority: 1,
    crit_enabled: false,
    inflicted_status: null,
    status_application_mode: null,
    status_proc_numerator: null,
    status_proc_denominator: null,
  },

  // --- Variable Pool Moves: ice ---
  ice_beam: {
    move_id: 'ice_beam',
    name: 'Ice Beam',
    type: 'ice',
    category: 'damage_plus_status',
    power: 90,
    accuracy: 100,
    priority: 0,
    crit_enabled: true,
    inflicted_status: 'freeze',
    status_application_mode: 'rolled',
    status_proc_numerator: 1,
    status_proc_denominator: 10,
  },
  frost_breath: {
    move_id: 'frost_breath',
    name: 'Frost Breath',
    type: 'ice',
    category: 'damage',
    power: 60,
    accuracy: 100,
    priority: 0,
    crit_enabled: true,
    inflicted_status: null,
    status_application_mode: null,
    status_proc_numerator: null,
    status_proc_denominator: null,
  },
  icy_wind: {
    move_id: 'icy_wind',
    name: 'Icy Wind',
    type: 'ice',
    category: 'damage',
    power: 55,
    accuracy: 95,
    priority: 0,
    crit_enabled: false,
    inflicted_status: null,
    status_application_mode: null,
    status_proc_numerator: null,
    status_proc_denominator: null,
  },

  // --- Variable Pool Moves: dragon ---
  dragon_pulse: {
    move_id: 'dragon_pulse',
    name: 'Dragon Pulse',
    type: 'dragon',
    category: 'damage',
    power: 85,
    accuracy: 100,
    priority: 0,
    crit_enabled: true,
    inflicted_status: null,
    status_application_mode: null,
    status_proc_numerator: null,
    status_proc_denominator: null,
  },
  outrage: {
    move_id: 'outrage',
    name: 'Outrage',
    type: 'dragon',
    category: 'damage',
    power: 120,
    accuracy: 100,
    priority: 0,
    crit_enabled: true,
    inflicted_status: null,
    status_application_mode: null,
    status_proc_numerator: null,
    status_proc_denominator: null,
  },
  draco_freeze: {
    move_id: 'draco_freeze',
    name: 'Draco Freeze',
    type: 'dragon',
    category: 'damage_plus_status',
    power: 70,
    accuracy: 90,
    priority: 0,
    crit_enabled: false,
    inflicted_status: 'freeze',
    status_application_mode: 'rolled',
    status_proc_numerator: 1,
    status_proc_denominator: 5,
  },
} satisfies Record<string, Move>

export function getMoveById(id: string): Move {
  const move = (MOVES as Record<string, Move | undefined>)[id]
  if (move === undefined) throw new Error(`Unknown move_id: "${id}"`)
  return move
}
